name: Docker
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  IMAGE_NAME: ops-base
  # The following env var can be used to configure the report
  # refs: https://github.com/aquasecurity/trivy-action/issues/142#issuecomment-1203093773
  # SARIF_ARGS: --severity CRITICAL

jobs:
  TestAndScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build images
        run: |
          docker buildx build --load . --tag $IMAGE_NAME:latest

      - name: Run Trivy vulnerability scanner in config mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          format: 'sarif'
          output: 'trivy-results-config.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '0'

      # Refs https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github
      - name: Upload Trivy config scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-config.sarif'
          category: Configuration

      - name: Run Trivy vulnerability scanner in docker mode
        # Run only on master branch, not on PRs, we want to upload the SARIF file only to the security tab and not in the MR.
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#        env:
#          SARIF_ARGS: --severity CRITICAL
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: '${{ env.IMAGE_NAME }}:latest'
          format: 'serif'
          output: 'trivy-results-docker.sarif'
          severity: 'CRITICAL'
          timeout: '15m'
          exit-code: '0'
          ignore-unfixed: true

      # Refs https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github
      - name: Upload Trivy image scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-docker.sarif'
          category: Image

  Deploy:
    needs: TestAndScan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3

      # Refs https://github.com/docker/login-action#github-container-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push images to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          docker buildx build --push . --platform "linux/amd64,linux/arm64" \
            --tag $IMAGE_ID:latest
